# Generated by Django 5.1.4 on 2025-10-22 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Envío')),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Pagado')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de Pago'), ('PAG', 'Pagado'), ('PRO', 'En Proceso'), ('ENV', 'Enviado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PEN', max_length=3, verbose_name='Estado')),
                ('id_transaccion', models.CharField(blank=True, help_text='ID proporcionado por la pasarela de pago (ej. Stripe, PayPal)', max_length=255, null=True)),
                ('direccion_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.direccion', verbose_name='Dirección de Envío')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre al Comprar')),
                ('precio_al_momento', models.DecimalField(decimal_places=2, help_text='Precio al que se compró la joya, sin importar cambios futuros.', max_digits=10, verbose_name='Precio Unitario de Compra')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Joya (Ref. Catálogo)')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
                'db_table': 'pedido_item',
            },
        ),
    ]
