# Generated by Django 5.1.4 on 2026-01-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_carrito_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='session_key',
        ),
    ]
