# Generated by Django 5.1.4 on 2025-10-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unidadmedida',
            table='unidad_medida',
        ),
    ]
