# Generated by Django 5.1.4 on 2026-01-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
