# Generated by Django 5.1.4 on 2026-01-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productoimagen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productoimagen',
            table='producto_imagen',
        ),
    ]
